'use client'

import './globals.css'
import Header from './components/Header/Header'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { WagmiConfig, createConfig, configureChains, mainnet } from 'wagmi'
import { goerli, optimism, optimismGoerli } from 'wagmi/chains'
import { alchemyProvider } from 'wagmi/providers/alchemy'
import { publicProvider } from 'wagmi/providers/public'


require('dotenv').config()
const inter = Inter({ subsets: ['latin'] })

const { chains, publicClient, webSocketPublicClient } = configureChains(
  [mainnet, optimism, goerli, optimismGoerli],
  [
    alchemyProvider({ apiKey: process.env.ETH_MAINNET_APIKEY! }),
    alchemyProvider({ apiKey: process.env.ETH_GOERLI_APIKEY! }),
    alchemyProvider({ apiKey: process.env.OP_MAINNET_APIKEY! }),
    alchemyProvider({ apiKey: process.env.OP_GOERLI_APIKEY! }),
    publicProvider(),
  ], //We can add private provide here 
)

const config = createConfig({
  autoConnect: true,
  publicClient,
  webSocketPublicClient,
})



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <WagmiConfig config={config}>
      <html lang="en">
        <body className={inter.className}>
          <Header />
          {children}
        </body>
      </html >
    </WagmiConfig>
  )
}
